# Generated by Django 4.2.16 on 2024-11-22 05:26

from django.db import migrations, models
import pgvector.django.vector
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('write_date', models.DateTimeField()),
                ('url', models.URLField(unique=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=256)),
            ],
        ),
    ]
