# Generated by Django 4.2.16 on 2024-11-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default='CAT', max_length=3, unique=True),
        ),
    ]
